java Stage1Test entrada.csv

main = Stage1Test
.java.class :
  javac *.java
  
classes = Stage1Test.java Joystick.java Operator.java

run:
  java main entrada.csv
  //java Stage1Test entrada.csv

clean:
  rm *.class
